language: python
python: 3.8
sudo: false
cache:
  pip: true
  directories:
    - eggs
env:
  # - PLONE_VERSION=4.3.x
  # - PLONE_VERSION=5.0.x
  - PLONE_VERSION=5.2.x
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#test-5.2.x#test-$PLONE_VERSION#" buildout.cfg
  - bin/buildout -N -t 5
before_script:  
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/test-coverage
  - bin/createcoverage
  - pip install coverage==3.7.1 coveralls
  - coveralls
