export const UNABLE_CONTACT_BACKEND = 'UNABLE_CONTACT_BACKEND';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const UPDATE_SEARCHABLE_TEXT = 'UPDATE_SEARCHABLE_TEXT';
export const UPDATE_SEARCHABLE_CATEGORY = 'UPDATE_SEARCHABLE_CATEGORY';
